name: counter_bot
services:
    counter_bot:
      environment:
        - DISCORD_BOT_TOKEN=MTE5NDAxNDgwNTA4Njk4MjI0Ng.GZaZkE.tNpPLmfEW1IFOeT4HDcSbPaxWFwd1tDQfTG7e0
        - DB_HOST=counter_db
        - DB_USERNAME=postgres
        - DB_PASSWORD=admin
        - DB_PORT=5432
        - DB_NAME=postgres
      container_name: counter_bot
      restart: always
      depends_on:
        - counter_db
      build: './'

    counter_db:
      environment:
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=admin
      container_name: counter_db
      restart: always
      ports:
        - 5444:5432
      volumes:
        - ./the_db_folder:/var/lib/postgresql/data
      build: './db'
